on: [push]

jobs:
  sync-with-gh-page:
    runs-on: ubuntu-latest
    name: Sync this repo with GH pages
    steps:
    - name: Checkout source repository
      uses: actions/checkout@v2
      with:
        path: source-repo
    - name: Checkout target repository
      uses: actions/checkout@v2
      with:
        repository: sampah92/sampah92.github.io
        path: target-repo
        token: c0118cba8ac4aefa6a1988da05d5a7059867cc9d
    - name: Sync the repo
      id: sync
      uses: tomasdelvechio/actions-push-repo-to-subdir@v1.2.0
      with:
        github-username: sampah92
        target-subdir-name: content/posts
