on: [push]

jobs:
  sync-with-gh-page:
    runs-on: ubuntu-latest
    name: Sync this repo with GH pages
    steps:
    - name: Checkout source repository
      uses: actions/checkout@v2
      with:
        path: source-repo
    - name: Checkout target repository
      uses: actions/checkout@v2
      with:
        repository: sampah92/sampah92.github.io
        path: target-repo
        token: 43cbf863ef51386a82d0b5610ebe7f4cd2f044d0
    - name: Sync the repo
      id: sync
      uses: tomasdelvechio/actions-push-repo-to-subdir@v1.2.0
      with:
        github-username: 'sampaph92'
        target-subdir-name: 'content/posts'
