on: [push]

jobs:
  sync-with-gh-page:
    runs-on: ubuntu-latest
    name: Sync this repo with GH pages
    steps:
    - name: Checkout source repository
      uses: actions/checkout@v2
      with:
        path: source-repo
    - name: Checkout target repository
      uses: actions/checkout@v2
      with:
        repository: sampah92/sampah92.github.io
        path: target-repo
        token: 9159fea9f129c55cb26e7df677c7a828fbcab3e3
    - name: Sync the repo
      id: sync
      uses: sampah92/sinkronisasi-repo@1.0
      with:
        github-username: sampah92
        target-subdir-name: content/posts
